In [1]:
import pandas as pd

In [5]:
df=pd.read_csv(r"C:\Users\SANJAY\Downloads\csv\pp.csv")

In [6]:
df

id  adClick  timeStamp  linkVisit  orderPlaced
0   1        0      1.800          1            1
1   2        0      2.500          0            1
2   3        1      3.010          0            1
3   4        1      4.900          0            0
4   5        0      5.080          1            0
5   6        1      6.001          1            1
6   7        0      7.900          0            1
7   8        0      8.550          0            1
8   9        1      9.660          0            0
9  10        1     10.770          0            1

In [13]:
x=df.iloc[:,0:4].values
y=df.iloc[:,4].values

In [16]:
x
y

array([1, 1, 1, 0, 0, 1, 1, 1, 0, 1], dtype=int64)

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=52)

In [18]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.fit_transform(x_test)

In [19]:
x_train

array([[ 1.45181591,  1.        ,  1.48954431, -0.77459667],
       [-0.55068879,  1.        , -0.37759573, -0.77459667],
       [-0.95118973,  1.        , -1.11896016, -0.77459667],
       [-1.75219161, -1.        , -1.5935903 ,  1.29099445],
       [-0.15018785, -1.        , -0.3069896 ,  1.29099445],
       [ 0.65081403, -1.        ,  0.7991732 , -0.77459667],
       [ 1.05131497, -1.        ,  1.05413981, -0.77459667],
       [ 0.25031309,  1.        ,  0.05427847,  1.29099445]])

In [20]:
from sklearn.ensemble import RandomForestClassifier 
model=RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)
#model=RandomForestClassifier(n_estimators=10, criterion='gini', random_state=0)
model.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [21]:
y_pred=model.predict(x_test)
from sklearn.metrics import confusion_matrix

In [22]:
cm=confusion_matrix(y_test, y_pred)
cm

array([[2]], dtype=int64)

In [23]:
cm=confusion_matrix(y_test, y_pred)
cm

array([[2]], dtype=int64)

In [24]:
from sklearn.metrics import accuracy_score
cm=accuracy_score(y_test, y_pred)
cm

1.0

In [25]:
from joblib import dump, load
dump(model, 'Dragon.joblib') 

['Dragon.joblib']

In [27]:
from joblib import dump, load
import numpy as np
model = load('Dragon.joblib') 
features = np.array([[11,0,11.08,0]])
model.predict(features)

array([0], dtype=int64)